 # Application server port
server:
  port: ${port:8080}
  servlet:
    contextPath: /roverservices
spring:
  application:
    name: roverservices
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration,org.redisson.spring.starter.RedissonAutoConfiguration
  profiles:
    active: dev